import Link from 'next/link'
import { getCategories } from '@/Services';
import React, { useState, useEffect } from 'react';
import Head from 'next/head';



const Header = () => {

  const [categories, setCategories] = useState([]);

  useEffect(() => {
    getCategories().then((newCategories) => {
      setCategories(newCategories);
    });
  }, []);

  return (
    <>
    <Head>
    <title>Blog || App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <div className='container mx-auto px-10 mb-8'>
      <div className='border-b w-full inline-block border-blue-400 py-8'>
        <div className="md:float-left block">
            <Link href="/">
                <span className="cursor-pointer font-bold text-4xl text-white">
                    Blog || App
                </span>
            </Link>
            <Link href="https://github.com/shreyzeous21" className='text-pink-500' title="Checkout my profile">Github</Link>
        </div>
        <div className="hidden md:float-left md:contents">
            {categories.map((category)=>(
                <Link key={category.slug} href={`/category/${category.slug}`}>
                    <span className="md:float-right mt-2 align-middle text-white ml-4 font-semibold cursor-pointer">
                        {category.name}
                    </span>
                </Link>
            ))}
        </div>
      </div>
    </div>
    </>
  )
}

export default Header
