import React from 'react'
import { Header } from '.'
import Head from 'next/head'

const Layout = ({children}) => {
  return (
    <>
    <Head>
    <title>Blog || App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
        <Header/>
        {children} 
    </>
  )
}

export default Layout
