/* eslint-disable @next/next/no-img-element */
import { getRecentPosts, getSimilarPosts } from "@/Services";
import moment from "moment";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { grpahCMSImageLoader } from "../../util";
import Head from "next/head";

const PostWidget = ({ categories, slug }) => {
  const [relatedPosts, setRelatedPosts] = useState([]);

  useEffect(() => {
    if (slug) {
      getSimilarPosts(categories, slug).then((result) => {
        setRelatedPosts(result);
      });
    } else {
      getRecentPosts().then((result) => {
        setRelatedPosts(result);
      });
    }
  }, [slug]);

  return (
    <>
      <Head>
        <title>Blog || App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white shadow-lg rounded-lg p-8 pb-12 mb-8">
        <h3 className="text-xl mb-8 font-semibold border-b pb-4">
          {slug ? "Related Posts" : "Recent Posts"}
        </h3>
        {relatedPosts.map((post, index) => (
          <div key={index} className="flex items-center w-full mb-4">
            <div className="w-16 flex-none">
              <img
                loader={grpahCMSImageLoader}
                alt={post.title}
                height="60px"
                width="60px"
                unoptimized
                className="align-middle rounded-full"
                src={post.featuredImage.url}
              />
            </div>
            <div className="flex-grow ml-4">
              <p className="text-gray-500 font-xs">
                {moment(post.createdAt).format("MMM DD, YYYY")}
              </p>
              <Link href={`/post/${post.slug}`} className="text-md" key={index}>
                {post.title}
              </Link>
            </div>
          </div>
        ))}
      </div>
    </>
  );
};
export default PostWidget;
